### ISSUE TITLE
Don't include structured information if empty?

### ISSUE THREAD

**Issue by The-Compiler** [peiTeX/qrbill#11]
The example from #10 contains an empty `//S1` at the end of the code as well as in the "Zusätzliche Informationen" part of the document. This (?) causes the [Postfinance validator](https://isotest.postfinance.ch/corporates/qrbill/validation) to complain:

> The element 'AltPmt' may only be delivered if it is actually filled.

for AV1 and AV2, and [swiss-qr-invoice.org](https://www.swiss-qr-invoice.org/validator/?lang=de) to say:

> Zeile 32, Feld RmtInf.AddInf.StrdBkgInf.Col5
> *
> das Format des Swico Feldes ist inkorrekt

It should probably not be included at all if no data fields for it have been set?

**Comment by TeXhackse** [comment]
You are right. That's a change in the validators which hasn't been there when we did the last checks. I will patch that.

**Comment by Tekki** [comment]
Seems PostFinance has its own interpretation of the standard. The qr codes are rejected only by them, SIX and all the bank apps I've tested accept them.

And by the way: Can you take a look at the printing position of AV2? At the moment it is printed on the same line as AV1 (code from commit d585f9d).

**Comment by The-Compiler** [comment]
As outlined above, [swiss-qr-invoice.org](https://www.swiss-qr-invoice.org/validator/?lang=de) doesn't seem to like it either, and I don't see any affiliation to PostFinance there.

**Comment by TeXhackse** [comment]
I am working on the removal anyway, so both should be fine afterwards. Just had some personal issues to resolve first. If everything goes as intented I will finish today and publish the release tomorrow. 

The strict Guideline says it only has to be delivered if its not empty. So the it's validating within the six's validator and those not accepting it are doing something wrong. But I think since both is acceptable via the standard it's okay to remove it.

**Comment by TeXhackse** [comment]
There is an officiel validator by six which i use as a reference.

**Comment by TeXhackse** [comment]
@The-Compiler I added a filter to avoid this. If possible please have a look and throw it into different validators. 

The `BillingInfo` field is now filtering for so called static data and will only add that if the rest of the data is not empty.

**Comment by Tekki** [comment]
I have a login at SIX and use their validator too. The unfortunate thing with PostFinance is that they have a very big customer base.

@The-Compiler Me personally, I would never upload any of my codes to such an obscure site.

And @TeXhackse take your time! I don't write here to create pressure on you.

**Comment by TeXhackse** [comment]
It's a bit annoying because the issue with version 2.1 was also mostly created by PostFinance … I still can't get why people simply cannot read the standard … Thanks @Tekki

**Comment by The-Compiler** [comment]
> I am working on the removal anyway, so both should be fine afterwards. Just had some personal issues to resolve first. If everything goes as intented I will finish today and publish the release tomorrow.

No hurry from my side. Glad to hear things seem to be better, and thanks for all your work!

> I added a filter to avoid this. If possible please have a look and throw it into different validators.

Thanks! Will give it a try as soon as I get around to it, but might be next week.

> Me personally, I would never upload any of my codes to such an obscure site.

It's not like there's anything interesting in there if I generate a dummy invoice to a fake customer - no need to upload real customer invoices, neither there nor in the Postfinance validator.

**Comment by TeXhackse** [comment]
@The-Compiler  did you have a look at the commit to remove that, does this resolve your issue?

I am a bit confused because e.g. the SIX compiler is throwing a warning now that I don't have to include the line even it it's not there. Their XML creation is a bit weird, and maybe that's the same for other validators.

**Comment by TeXhackse** [comment]
As far as I can see this should be resolved.

**Comment by The-Compiler** [comment]
I'm afraid I couldn't get the locally installed version to work properly (that's probably just an issue on my side though...), so I wasn't able to test this. I'm very busy with other stuff currently (semester starting soon at the university I work at), so I probably won't get around to testing this right now. Sorry, and thanks for the fix anyways!

**Comment by TeXhackse** [comment]
I think it should be fine I ran a bunch of tests here - so if you manage to get the update (guess it will be on CTAN tomorrow) I am glad to get further feedback, but I expect its fine.
