### ISSUE TITLE
qrcode placement problems with separate=symbol

### ISSUE THREAD

**Issue by oetiker** [peiTeX/qrbill#2]
according to https://testplattform.postfinance.ch/ the placement of the qr code and the field below it are not quite correct.

[tshirt-6-2020-08-22-23-57-32_Visuelle_Kontrolle.pdf](https://github.com/peiTeX/qrbill/files/5113110/tshirt-6-2020-08-22-23-57-32_Visuelle_Kontrolle.pdf)

**Comment by TeXhackse** [comment]
Thanks for the report, I will have a look and resolve this during the day.
