### ISSUE TITLE
account and reference spacing

### ISSUE THREAD

**Issue by oetiker** [peiTeX/qrbill#4]
Account numbers and Reference numbers on the 'official' QRBills come with extra spacing

`CH12\,3000\,0001\,4600\,4948\,4`

`00\,00000\,00000\,00000\,00000\,00152`

**Comment by TeXhackse** [comment]
I've added 4 options to achieve this. This configuration is not activate by default but you can find an example in the documentation

```
 sep-iban=4,sep-reference=-5
```
