### ISSUE TITLE
user friendly IBAN format

### ISSUE THREAD

**Issue by viktoriasee** [peiTeX/qrbill#6]
### Requirements
It seems to be a requirement by the standard that the IBAN is strictly 21 digits within the QR code. It is a requirement by ergonomics that in the human readable part of the payment slip the number is devided into blocks . 

### Current behaviour
If I enter the IBAN without spaces they are not apparent in the human readable part of the payment slip. If we enter the IBAN with spaces, they appear on the human readable part but the validation of the QR code fails.

### Proposed solution
I think the user friendly behaviour is like this: 
* Strip the spaces before feeding the QR code generator. 
* Add spaces (thin spaces?) in the human readable part if not present. i.e. CH68 0900 0000 1234 5678 0

I checked with this validator: https://www.swiss-qr-invoice.org/

**Comment by viktoriasee** [comment]
Duplicate of #4

**Comment by TeXhackse** [comment]
It's not reallly a duplicate because it's much simpler and of interest for non-swiss users. I will reopen this because this is something which I can add with the update for the support of swiss standard version 2.2.

**Comment by viktoriasee** [comment]
At the time of writing I did not see that there are the options `sep-iban` and `sep-reference`. To me it makes no sense to default those to 0. I would rather set them to something like 4 or 5. This would make life of 90% users easier.

**Comment by TeXhackse** [comment]
Oh, I forgot about that :D 

As you might realize: I don't have a swiss bank acocunt, that's why I can use it for myself anyway. 

The schemes differ for each country, but I can adjust it in the example to use a non zero value.
