### ISSUE TITLE
Additional information contains unneeded text

### ISSUE THREAD

**Issue by Adrian-Hirt** [peiTeX/qrbill#9]
Using this package with the `qrbill scrletter example` generates a PDF which contains (probably) superfluous text (probably in the form of the BillingInfo, which is composed of multiple other fields such as the `invoicedate` and the `invoicenum`).

![screenshot](https://user-images.githubusercontent.com/13788379/177341315-7fcc7757-a87a-49df-97bb-b841bf14b16a.png)

Also see the attached PDF for the complete file:

[QRbill_2 (1).pdf](https://github.com/peiTeX/qrbill/files/9046787/QRbill_2.1.pdf)

Finally, here's the code that generated the attached file, which is just the example from the qrbill.pdf from CTAN.

```tex
\documentclass[foldmarks=b]{scrletter}
\usepackage[
  frame=top,
  sep-iban=4,
  sep-reference=-5,
  separate=symbol
]{qrbill}

% Setup layer
\DeclareNewLayer[
  align=bl,
  voffset=\paperheight,
  hoffset=0pt,
  contents={\QRbill},
  width=\paperwidth,
  height=105mm,
]{qrbill}
\begin{document}
  \qrbillsetdata{
  creditor*={foobar LLC\\
  Postfach\\
  404\\
  2342\\
  Zurich\\
  CH},
  Account=CH1280808005649899718,
  vat=123123123,% VAT number with stripped CH and periods
  debtor*={peiTeX\\
  TeXnikerweg\\
  78\\
  23420\\
  Hamburg\\
  DE},
  Amount=1337.42,
  Message=Bestellung vom 27.06.2020,
  invoicenum=100-4242,
  invoicedate=200701,%yymmdd
  vatdetails=0,% 0% VAT
  vatdate=200701%yymmdd
  }
  \setkomavar{fromaddress}{\insertcreditor}
  \begin{letter}{\insertdebtor}
  \opening{opening}snip
  Text
  \closing{closing}
  % Add qbill on last page
  % For more details
  \AddLayersToPageStyle{@everystyle@}{qrbill}
  \end{letter}
\end{document}
```

Is this intended, that this text is shown? If yes, how can I remove the text?

Other than that, this package works great, thanks a lot!

**Comment by TeXhackse** [comment]
It is intended. The standard requires all encoded information to be shown on the “human readable” part as well. 

E.g. have a look at the official documentation. I know that not everyone is sticking that strictly to the standard but this was of the ideas behind this package to allow the implementation of all requirements and not only those making banking apps reading the codes.

The examples of six, e.g. at https://www.six-group.com/de/newsroom/media-releases/2020/20200609-qr-bill-launch.html also use it.,

**Comment by Adrian-Hirt** [comment]
Thanks for the fast reply! I did not yet look at the official documentation, interestingly that part was missing on all the QR bills I used so far, seems like not everyone is adhering to the standard. In that case I close the issue, thanks for the cool LaTeX package :)
